### ISSUE TITLE
Implement `__contains__` in `Env`

### ISSUE THREAD

**Issue by hukkinj1** [sloria/environs#113]
## Feature request
Would be nice if we could do
```python
env = Env()
if "SOME_ENV_VAR" in env:
    ....
```
to check if an env variable exists. I.e. implement the `__contains__` dunder method.

The benefit of this compared to `"SOME_ENV_VAR" in os.environ` is that it could be used in a `with env.prefixed("PREFIX"):` statement.

**Comment by sloria** [comment]
Sounds fine, but I'm not 100% what the expected behavior would be for unparsed variables. Would you expect `"SOME_VAR" in env` to return `True` is `"SOME_VAR"` has not yet been parsed? In the context of [deferred validation](https://github.com/sloria/environs#deferred-validation), one might expect the membership check to only return `True` for parsed variables, though I'm not confident about it.

**Comment by hukkinj1** [comment]
I was expecting this to run code similar to `_get_from_environ()` but return a bool instead. That is simply check if an env variable exists. No parsing, checking parsed, or storing anything to parsed variables.

But I can definitely see your point. This could be expected to make a check to parsed variables.

**Comment by sloria** [comment]
I'm not sure the benefits are worth the added API surface and possible user confusion. Does `"SOME_VAR" in os.environ` suffice to meet your use case?

**Comment by sloria** [comment]
Closing for now. Feel free to continue discussion if you still think it's a good idea
