### ISSUE TITLE
Set default value once and reuse

### ISSUE THREAD

**Issue by konoufo** [sloria/environs#17]
Coming from django-environ, I thought  `env(varname, "defaultval")` would set a default to be automatically used on subsequent calls to `env(varname)`. There should be a way to set a default value for an environment var, to be overrided or not on subsequent calls. Something like `env.setdefault('varname', "originaldefault")` would do; then if `varname` is not defined in environment, susbsequent calls to `env("varname")` would output `"originaldefault"` instead of raising the usual exception.

**Comment by sloria** [comment]
I don't recommend using `env(...)` directly in your application code. Better to parse your env vars once in a settings file.

```python
# settings.py

DEBUG = env.bool("DEBUG", default=False)
```

```python
# app.py

if settings.DEBUG:

    #...
```

environs doesn't support the use case of calling `env(...)` multiple times for the same env var, which is why we decided to [drop the schema API found in django-environ and envparse](https://github.com/rconradharris/envparse/issues/12#issuecomment-214729943).

**Comment by konoufo** [comment]
I understand the philosophy. Alright, I'll close this.
