### ISSUE TITLE
Bringing environments to subprocess

### ISSUE THREAD

**Issue by josephlim75** [sloria/environs#257]
I am not sure if this feature already exists, I wanted to make sure that environments that is set using `env("VAR", "VALUE")` is able to passed to `subprocess.run` or `subprocess.Popen`.  

## Not working
```
env.str("VAR", "VALUE")
args = shlex.split("someshell.sh --someFlag --verbose")
subprocess.run(args)

# output inside someshell.sh
echo $VAR 
$ (empty)
```
The sample code above output empty value when echoing `$VAR` whereas if i change `env.str()` to `os.environ`, it is working as expected.  How do I pass the `env` values to `subprocess`

## Working
```
os.environ["VAR"] = "VALUE"
args = shlex.split("someshell.sh --someFlag --verbose")
subprocess.run(args)

# output inside someshell.sh
echo $VAR
$ VALUE
```

**Comment by bvanelli** [comment]
Isn't this related to the fact that you are using the default value in the first example?

```
env.str("VAR", "VALUE")
```

Is not the same as:

```
os.environ["VAR"] = "VALUE"
```

Indeed, default values are not set to the current environment, in bash this would be the same as writing:

```
$ echo ${VAR-VALUE}
VALUE
$ VAR=123
$ echo ${VAR-VALUE}
123
```

When you load variables from the .env with load_env those are populated on your environment, so that would work, but default values not. I'm not sure where that could be solved. But as I said, if you use default variables on your python script, you have three options:

- Overwrite the actual value with the default: `os.environ["VAR"] = env.str("VAR", "VALUE")`
- Provide the variable directly to the script (be aware of bash encoding): `args = shlex.split(f"VAR={env.str('VAR', 'VALUE')} someshell.sh --someFlag --verbose")`
- Or the simplest, use the default value on bash too: `echo ${VAR-VALUE}`

**Comment by sloria** [comment]
@bvanelli is correct--the environment variable needs to be set explicitly. environs does not set envvars
