### ISSUE TITLE
env.dump() only shows pre-loaded variables

### ISSUE THREAD

**Issue by garettmd** [sloria/environs#82]
I just started using environs, so let me know if I'm not understanding the best way to use it, but what I expect `env.dump()` to do is dump all the variables from .env. It appears that it only dumps variables which have already been called on (i.e. `env('FLASK_APP')`), and only then will it appear in the output of `env.dump()`. Is there/could there be a way to just show all the contents of a .env file in a dict without explicitly loading them? Or maybe I'm missing the correct usage of this?

**Comment by sloria** [comment]
Yes, the behavior is by design. `env.read_env` just adds the envvars in `.env` to `os.environ`. Parsing and validation happens with subsequent `env.*` method calls.

If you just want to get your `.env` values as a dict, you might want to look into using python-dotenv's `DotEnv.dict()` directly: https://github.com/theskumar/python-dotenv/blob/d0a219d180ec62bfb1bead5849aecca91eead3d9/src/dotenv/main.py#L55

**Comment by garettmd** [comment]
Thanks for the explanation @sloria
